### ISSUE TITLE
<Trabajo realizado Hito 4: "Corrección pruebas  unittest">

### ISSUE THREAD

**Issue by mrojas32** [Chopan22/GRP-TheEmoticons-2024-PROYINF#10]
Dentro del trabajo realizado en el hito 4, se procese a corregir el test con unittest, dado que se identificó el siguiente incoveniente:

-Se precisaba de tener estar autenticado para realizar los test´s.

Para solucionar esto se modificó el código (testing.py). Además, se adjuntan los resultados de la ejecución del test.

**Comment by MatiTorres17** [comment]
El tiempo empleado para realizar esta corrección fue de 3 horas.

Se adjunta imagen de las 4 pruebas superadas de manera correcta y sus peticiones se ven reflejadas en el backend:
![Testing](https://github.com/user-attachments/assets/904d60a8-cac1-4db2-b182-914c8eb2caab)
