### ISSUE TITLE
<HU-2"Visualización DICOM con Perspectivas y Filtros">

### ISSUE THREAD

**Issue by josebeltran1** [Chopan22/GRP-TheEmoticons-2024-PROYINF#2]
# Historia de Usuario

- **Como** radiólogo en un centro médico, 
**quiero** poder visualizar imágenes DICOM desde distintas perspectivas ortogonales a través de una interfaz intuitiva, además de tener la capacidad de aplicar filtros específicos a las imágenes para resaltar detalles importantes, 
**para** poder entender mejor las estructuras anatómicas y así ofrecer un diagnóstico más preciso y un análisis más exhaustivo.

## Criterios de Aceptación

- **Dado** que soy un radiólogo revisando una radiografía de un paciente, 
**cuando** selecciono una opción para cambiar la dirección de la vista a una de las perspectivas ortogonales disponibles,
**entonces** el sistema debe actualizar la visualización de la imagen a la dirección seleccionada sin pérdida de calidad, lo cual es fundamental para garantizar un diagnóstico correcto.

- **Dado** que soy un radiólogo utilizando la interfaz para aplicar filtros, 
**cuando** elijo la opción "filtrar" en la imagen, 
**entonces** el sistema debe organizar la información de la imagen en secciones claras y permitir la aplicación de filtros que resalten detalles relevantes para facilitar un análisis más estructurado y eficiente.

**Comment by josebeltran1** [comment]
Criterio de aceptación 1: Estimación: 5
Este criterio requiere manejo de imágenes y actualizaciones en tiempo real, lo que puede implicar desafíos técnicos, pero no es tan complejo como la aplicación de filtros.

Criterio de aceptación 2: Estimación: 8
La implementación de filtros y organización de la información en secciones claras puede ser más compleja debido a los diferentes tipos de filtros y la necesidad de mantener una interfaz intuitiva.

Criterio de aceptación 3: Estimación: 5
Aunque similar al Criterio 1 en términos de mantener la calidad de la imagen, este criterio también implica proporcionar información sobre los filtros, lo cual añade un poco más de complejidad.

**Comment by mrojas32** [comment]
Trabajo realizado Hito 4: "Avances HU-2"

Durante el hito 4 se desarrolló la visualización DICOM con perspectivas y filtros, logrando la aplicación de los siguientes filtros:
-Brillo
-Contraste
-Sepia
-Invertir
-Hue-Rotate

Además se desarrolló  la funcionalidad de rotación y zoom, esta última se puede efectuar por medio de una barra de zoom, como con la rueda del mouse. Además, se puede arrastrar la imagen con el click derecho del mouse.

El trabajo correspondiente a la observación del examen desde otras perspectivas (en este caso 3D), se realizó, pero no se llegó al resultado ni funcionalidad esperada, por ende se abordará nuevamente en el siguiente hito.

El tiempo utilizado para el desarrollo de esta HU fue de 5 horas.
